# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Collaborative knowledge base
email: riccardo.casatta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This project aim crate a tool to easy create and mantain a collaborative knowledge base using a basic static site editable from github.
baseurl: "/knowledge-base" # the subpath of your site, e.g. /blog
url: "http://riccardo.casatta.it" # the base hostname & protocol for your site
twitter_username: rcasatta
github_username:  rcasatta

# Build settings
# markdown: kramdown

# looks the following setting has problems with pages
# permalink: /:year/:month/:day/:title/

permalink: pretty


github:
  repo: https://github.com/RCasatta/knowledge-base
  editpost: https://github.com/RCasatta/knowledge-base/edit/gh-pages/
